apps/blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^articles/$', views.ArticleListView.as_view(), name='article_list'),
    url(r'^articles/(?P<pk>\d+)/$', views.ArticleDetailView.as_view(), name='article_detail'),
]

project/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^', include('apps.blog.urls', namespace='blog')),
    url(r'^about/$', views.about),
    url(r'^admin/', admin.site.urls),
    url(r'^summernote/', include('django_summernote.urls')),
]

# 配置: django-debug-toolbar

if 'debug_toolbar' in settings.INSTALLED_APPS:
    import debug_toolbar

    # 应该插入到 urlpatterns 最前面
    urlpatterns.insert(0, url(r'^__debug__/', include(debug_toolbar.urls)))

    # 使用 gunicorn 部署测试服务器时，静态文件不能正确返回，需要加上下面的代码
    # 参考文档:
    # * https://docs.djangoproject.com/en/1.11/ref/contrib/staticfiles/#django.contrib.staticfiles.urls.staticfiles_urlpatterns
    # * https://stackoverflow.com/questions/12800862/how-to-make-django-serve-static-files-with-gunicorn/12801140#12801140
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += staticfiles_urlpatterns()

    # 配置: django-summernote
    # https://docs.djangoproject.com/en/1.11/topics/files/
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/blog/models.py
from django.contrib.postgres.fields.array import ArrayField
from django.db import models


class ArticleManager(models.Manager):
    def article_list(self, request):
        if request.user.is_authenticated:
            return self.filter(status__in=(Article.STATUS_PUBLISHED, Article.STATUS_PRIVATE))
        else:
            return self.filter(status=Article.STATUS_PUBLISHED)


class Article(models.Model):
    STATUS_DRAFT = 'D'
    STATUS_PUBLISHED = 'P'
    STATUS_PRIVATE = 'I'

    STATUS_CHOICES = (
        (STATUS_DRAFT, '草稿'),
        (STATUS_PUBLISHED, '已发布'),
        (STATUS_PRIVATE, '私密'),
    )

    TOP_CHOICES = zip(range(3, -4, -1), map(str, range(3, -4, -1)))

    title = models.CharField('标题', max_length=200)
    content = models.TextField('正文')
    abstract = models.CharField('摘要', max_length=250)
    status = models.CharField('状态', max_length=1, default=STATUS_PUBLISHED, choices=STATUS_CHOICES)
    order = models.PositiveSmallIntegerField('排序', default=0, choices=TOP_CHOICES)
    tags = ArrayField(models.CharField(max_length=20), size=10, verbose_name='标签')
    create_at = models.DateTimeField('创建时间', auto_now_add=True)
    updata_at = models.DateTimeField('更新时间', auto_now=True)

    objects = ArticleManager()

    class Meta:
        verbose_name = '文章'
        verbose_name_plural = '文章'
        ordering = ['-order', '-create_at']

    def __str__(self):
        return self.title

apps/blog/views.py
from django.views.generic import ListView, DetailView

from .models import Article


class HomeView(ListView):
    template_name = 'blog/home.html'
    paginate_by = 10

    def get_queryset(self):
        return Article.objects.article_list(self.request)


class ArticleListView(ListView):
    template_name = 'blog/article_list.html'
    paginate_by = 50

    def get_queryset(self):
        return Article.objects.article_list(self.request)


class ArticleDetailView(DetailView):
    model = Article
    template_name = 'blog/article_detail.html'

project/views.py
from django.shortcuts import render


def about(request):
    return render(request, 'home.html')

apps/blog/templates/blog/article_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ article.title }}</h1>
    <p>{{ article.content|safe }}</p>
{% endblock %}

apps/blog/templates/blog/home.html
{% extends 'base.html' %}

{% block content %}
    <div class="col-xs-10 col-sm-10 col-md-10 col-lg-10">
        <h4 class="pannel-heading">共 100 篇文章</h4>
        {% for article in article_list %}
            <div class="panel panel-info">
                <h2 class="pannel-heading"><a href="{% url 'blog:article_detail' article.id %}">{{ article.title }}</a></h2>
                <hr>
                <div class="panel-body">
                    {{ article.abstract|safe }}
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="col-xs-2 col-sm-2 col-md-2 col-lg-2">
        <h4 class="pannel-heading">标签</h4>
    </div>
{% endblock %}

project/templates/base.html
{% extends "bootstrap3/bootstrap3.html" %}

{% load static %}

{% block bootstrap3_extra_head %}
    <link rel="stylesheet" href="{% static 'app.css' %}">
{% endblock %}

{% block bootstrap3_content %}
    <div class="container">
        <div class="page-header">
            <h1>超越干越
                <small>我的文章</small>
            </h1>
        </div>
        {% block content %}{% endblock %}
    </div>
{% endblock %}

project/templates/home.html
{% extends "base.html" %}

{% block content %}
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">欢迎使用 django-project-template</h3>
        </div>
        <div class="panel-body">
            主页
            <a href="https://github.com/huyx/django-project-template">
                https://github.com/huyx/django-project-template
            </a>
        </div>
    </div>
    <div class="panel panel-info">
        <div class="panel-heading">
            <h3 class="panel-title">已安装应用</h3>
        </div>
        <div class="panel-body">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>应用</th>
                    <th>版本</th>
                </tr>
                </thead>
                <tbody>
                {% for name, version in app_versions.items %}
                    <tr>
                        <td>{{ name }}</td>
                        <td>{{ version|default:'-' }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}